### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by acronce** [johnboiles/home-assistant-purpleair#4]
Thanks for this integration! Up until May 26 it has worked well.

Unfortunately now I'm seeing these errors in the log:

```
Traceback (most recent call last):
  File "/config/custom_components/purpleair/PurpleAirApi.py", line 142, in _update
    results = await self._fetch_data(public_nodes, private_nodes)
  File "/config/custom_components/purpleair/PurpleAirApi.py", line 130, in _fetch_data
    json = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://purpleair-over-quota-2.appspot.com/')
```

And 

```
bad API response for https://www.purpleair.com/json?show=60663: 500
bad API response for https://www.purpleair.com/json?show=60663: 429
```

If I try going to the above URL in a browser, it redirects to https://purpleair-over-quota-2.appspot.com and provides the following error:

```
Error: Server Error

The server encountered an error and could not complete your request.
Please try again in 30 seconds.
```

As a diagnostic I tried going through the integration instructions with another sensor from the map, but there no longer is a "JSON" link at the bottom of the widget box. So I tried copying out the JSON by hand and pasting it in the integration, but that didn't work.

Seems like things have changed on the Purple Air side that have broken this integration. Any thoughts on how to get this to work again?

**Comment by lukasz-karolewski** [comment]
@johnboiles old endpoints have been deprecated, this integration needs to be migrated to new api 

https://community.purpleair.com/t/making-api-calls-with-the-purpleair-api/180
https://api.purpleair.com/#api-welcome-using-api-keys

Are you willing to accept PR's, you want to work on it yourself or should I just fork and make my own version?

**Comment by kaned** [comment]
@lukasz-karolewski if you end up branching would you mind noting here? I have my new read key, but no time to branch and fix the integration myself at the moment.

**Comment by johnboiles** [comment]
I am def willing to accept PRs!

**Comment by catchdave** [comment]
I made a fork of this that gets the data from local polling only, so won't be affected by future API changes, if anyone is interested: https://github.com/catchdave/home-assistant-purpleair
